#!/usr/bin/env bash
# vim: filetype=sh

nmcli -c no -g all d | grep -vE '(externally|p2p)' | \
  jq -acrsR 'split("\n") | map(split(":")) | 
  map({"network": .[0],
       "type": .[1],
       "connection": .[6]}) | .[] | select(.network != null)' \
         | jq -r '.connection'

