#!/bin/sh

alias \
    update="topgrade --cleanup --no-retry --yes && trash-empty && nix-collect-garbage" \
    remove="echo '\033[0;31m]WARNING: FORCED UNINSTALLING' && yay -Rddns" \
    si="pacman -Q | grep" \
    ungz="tar -zxvf" \
    unxz="tar -xf" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -v" \
    mkdir="mkdir -pv" \
    md="mkdir" \
    theme="~/.config/scripts/theme.sh" \
    pipes="~/.config/scripts/pipes.sh" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x" \
    myip="curl ipinfo.io/ip && printf '\n'" \
    pacman="sudo pacman" \
    free="free -h" \
    ysy="yay" \
    yya="yay" \
    ayy="yay" \
    yys="yay" \
    ya="yay" \
    pacmna="pacman" \
    pacma="pacman" \
    pcman="pacman" \
    pcaman="pacman" \
    pc="cp" \
    vm="mv" \
    dc="cd" \
    mr="rm" \

