#!/bin/sh

alias \
    update="topgrade --cleanup --no-retry --yes" \
    bandwidth="~/.config/scripts/bandwidth.sh" \
	cache="~/.config/scripts/cache-clean.sh" \
	cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -v" \
    mkdir="mkdir -pv" \
    md="mkdir" \
    pipes="~/.config/scripts/pipes.sh" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x" \
    myip="curl ipinfo.io/ip && printf '\n'" \
    ccat="highlight --out-format=ansi" \
    starwars="telnet towel.blinkenlights.nl" \
	simplettt="~/.config/scripts/simplettt.sh"
