#!/bin/bash
printf "\033[1;33mWARNING: THIS IS GOING TO MOVE MOST OF YOUR CONFIG FILES TO A BACKUP DIRECTORY: %s/config_backup\033[1;0m\n" "$HOME"
printf "Are you sure that you want to continue? (y/N): "
read -r choice
[ "$choice" == "n" ] || [ -z "$choice" ] && printf "Ok, you will install manually\n" && exit
printf "Installing...\n"

cwd=$(pwd)
configdir=".config"
[ -d "$HOME/$configdir" ] || mkdir -p "$HOME/$configdir" >/dev/null
[ -d "$HOME/config_backup" ] || mkdir -pv "$HOME/config_backup" >/dev/null

local_dirs=("home" "config" "bin" "share")
system_dirs=("" "$configdir" ".local/bin" ".local/share")

for i in {0..3}; do
	local_files=$(find "${local_dirs[$i]}" -maxdepth 1 -printf "%f\n" | tail -n+2)
	system_files=$(find "$HOME/${system_dirs[$i]}" -maxdepth 1 -printf "%f\n" | tail -n+2)
	for f in $local_files; do
		df=$(echo "$system_files" | grep -e "^$f$")
		[ -z "$df" ] || mv "$HOME/${system_dirs[$i]}/$df" "$HOME/config_backup"
		ln -vs "$cwd/${local_dirs[$i]}/$f" "$HOME/${system_dirs[$i]}"
	done
done

# backing up other files
mv "$HOME/.zshrc" "$HOME/config_backup"
ln -vs "$cwd/config/zsh/.zshrc" "$HOME"
# mkdir -p "$HOME/.mozilla/firefox/config/fontconfig"
# mv $HOME/.var/app/org.mozilla.firefox/config/fontconfig/fonts.conf $HOME/config_backup
# ln -vs "$cwd/other/fffonts.conf" "$HOME/.mozilla/firefox/config/fontconfig/fonts.conf"
# mv "$HOME/.mozilla/firefox/config/fontconfig/fonts.conf" "$HOME/config_backup"
# $HOME/.var/app/org.mozilla.firefox/config/fontconfig/fonts.conf

printf "Installed correctly!\n"
# printf "You should also
# \tsudo mv -t $HOME/config_backup /etc/{tlp.conf,environment}; sudo ln -s $cwd/etc/tlp.conf /etc; sudo ln -s $cwd/etc/environment /etc; sudo ln -s $cwd/etc/libinput.conf /etc; sudo ln -s $cwd/etc/envars.sh /etc/profile.d\n"
# printf "And wget \"https://cdn.wallpapersafari.com/45/94/AyVLsg.jpg\" $HOME/Pictures/doom-dark.jpg\n"
# ln -s $cwd/config/alacritty/alacritty.gruvbox.dark $configdir/alacritty/alacritty.yml
