- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'
- name: Paru (for AUR packages)
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: paru-bin
    use: makepkg
    state: present

- name: System and essential services
  become: yes
  pacman:
    name:
      - ansible
      - base
      - base-devel
      - bluez
      - bootconfig
      - btrfs-progs
      - dhcpcd
      - git
      - go
      - gocryptfs
      - hostapd
      - hyperv
      - intel-media-driver
      - intel-speed-select
      - intel-ucode
      - jdk21-openjdk
      - libfprint
      - libva-intel-driver
      - libva-utils
      - linux
      - linux-firmware
      - linux-headers
      - mesa-utils
      - networkmanager
      - openssh
      - pacman-contrib
      - rust
      - sbctl
      - snapshot
      - sof-firmware
      - stow
      - sudo
      - systemd-resolvconf
      - tailscale
      - ufw
      - vulkan-intel
      - vulkan-tools
      - x86_energy_perf_policy
      - xf86-video-vesa
      - zram-generator
    state: present
- name: (AUR) System and essential services
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - epson-inkjet-printer-201211w
      - proot
    state: present
    use: paru

- name: Desktop environment
  become: yes
  pacman:
    name:
      - alacritty
      - bluez-utils
      - brightnessctl
      - cliphist
      - firefox
      - gdm
      - gnome-control-center
      - greetd-regreet
      - hyperfine
      - hyperv
      - hypridle
      - hyprland
      - hyprlock
      - hyprpaper
      - imv
      - libnotify
      - mako
      - mpv
      - nemo
      - nemo-share
      - nwg-look
      - nwg-shell-config
      - pipewire
      - pipewire-alsa
      - pipewire-jack
      - pipewire-pulse
      - playerctl
      - qalculate-gtk
      - rofi-calc
      - rofi-emoji
      - rofi-rbw
      - rofi-wayland
      - syncthing
      - uwsm
      - waypipe
      - wayvnc
      - wireplumber
      - wl-clipboard
      - xdg-desktop-portal-hyprland
      - xdg-user-dirs
      - ydotool
    state: present
- name: (AUR) Desktop environment
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - appimagelauncher
      - better-control-git
      - eww
      - grimshot-bin-sway
      - hyprshade
      # - moonlight-qt-bin
      - overskride-bin
      - phinger-cursors
      - pyprland
      # - sioyek-appimage
      - sunshine
      - swayosd-git
      # - tela-icon-theme-bin
      - vigiland-git
      - walker-bin
      - waydroid
      - waydroid-helper
      - whitesur-gtk-theme
      - wlogout
      - wshowkeys-git
      - xwaylandvideobridge
    state: present
    use: paru

- name: Fonts
  become: yes
  pacman:
    name:
      - ttf-dejavu-nerd
      - ttf-jetbrains-mono
      - ttf-jetbrains-mono-nerd
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-mono
      - ttf-noto-nerd
      - ttf-ubuntu-mono-nerd
      - ttf-ubuntu-nerd
    state: present

- name: Graphical Apps
  become: yes
  pacman:
    name:
      - arduino-ide
      - baobab
      - discord
      - gimp
      - obs-studio
      - obsidian
      - prismlauncher
      - pulseview
      - qtcreator
      - rnote
      - scrcpy
      - spotify-launcher
      - telegram-desktop
      - xournalpp
    state: present
- name: (AUR) Graphical Apps
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - affine-bin
      - android-studio
      - anydesk-bin
      # - bambustudio-bin
      - brave-bin
      - discord-canary-wayland-hook
      - floorp-bin
      - localsend-bin
      - ltspice
      # - orca-slicer-bin
      # - sigrok-firmware-fx2lafw-bin
      # - sioyek-appimage
      - skypeforlinux-bin
      - steam
      - universal-android-debloater-bin
      - vesktop-bin
      - visual-studio-code-bin
      - flite
      - xmcl-launcher
      - zotero
    state: present
    use: paru

- name: Command line
  become: yes
  pacman:
    name:
      - bat
      - bc
      - bluez-utils
      - brightnessctl
      - btop
      - cage
      - cpupower
      - cyme
      - dialog
      - dmidecode
      - duf
      - eza
      - fd
      - flatpak
      - git
      - man-db
      - man-pages
      - ncdu
      - nmap
      - pdftk
      - ranger
      - ripgrep
      - rsync
      - rustscan
      - simple-scan
      - socat
      - sshfs
      - starship
      - stow
      - strace
      - stress
      - sudo
      - tmon
      - tree
      - turbostat
      - unzip
      - usbip
      - zip
      - zsh
    state: present

- name: Development
  become: yes
  pacman:
    name:
      - afl-utils
      - android-tools
      - arduino-language-server
      - docker
      - docker-compose
      - doxygen
      - git
      - go
      - hugo
      - john
      - just
      - lua-language-server
      - minicom
      - neovim
      - pandoc-cli
      - pyright
      - pdftk
      - rust
      - rust-analyzer
      - texlive
      - tk
    state: present
- name: (AUR) Development
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      # - ltspice
      - slint-lsp-bin
    state: present
    use: paru

