#! /bin/sh

pkill -USR1 -x sxhkd || sxhkd &
feh --bg-fill ~/Downloads/mikasa.png # https://images7.alphacoders.com/632/632843.png
~/.config/polybar/launch.sh
pkill -USR1 -x picom --experimental-backends --backend glx || picom --experimental-backends --backend glx & # picom with blur
pkill -USR1 -x dunst || dunst &
dconf reset -f /org/gnome # fix gtk-apps slow loading
redshift -oP 4400K
setxkbmap -layout "us" -option "ctrl:nocaps,compose:menu" # set keyboard layout and compose key 

# mouse
xset +dpms
#xset m 0 0
xinput set-prop pointer:"Micro-Star INT'L CO., LTD MSI GM11 Gaming Mouse" "libinput Accel Speed" +0.1 # speed
xinput set-prop pointer:"Micro-Star INT'L CO., LTD MSI GM11 Gaming Mouse" "libinput Accel Profile Enabled" 0, 1 # disable acceleration

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap					16
bspc config top_padding					26

# gruvbox colors
bspc config focused_border_color \#d79921
bspc config normal_border_color \#282828
bspc config presel_feedback_color \#d79921

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

