#!/bin/sh
curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
mkdir -pv "${XDG_DATA_HOME:-$HOME/.vim/autoload}"
cp "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim "${XDG_DATA_HOME:-$HOME/.vim}"/autoload/plug.vim

# install packer for windows.nvim
mkdir -pv ~/.local/share/nvim/site/pack/packer/start
git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
