#!/bin/sh
mkdir -pv "$HOME/.local/share/autoload"
curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
mkdir -pv "${XDG_DATA_HOME:-$HOME/.vim/autoload}"
cp "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim "${XDG_DATA_HOME:-$HOME/.vim}"/autoload/plug.vim
