config-version = 2

start-at-login = false

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]
alt-left = 'focus left'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'

alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'

alt-h = 'split horizontal'
alt-v = 'split vertical'
alt-f = 'fullscreen'
alt-q = 'close'
alt-space = 'layout floating tiling'
alt-s = 'layout v_accordion h_accordion'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Calculator'
run = 'layout floating'
