#!/bin/sh

# commands
alias \
	grep="grep --color" \
	ls="exa --group-directories-first" \
	ll="ls -lSh" \
	lls="clear; ls" \
	l="ll -a" \
	la="ls -a" \
	cp="cp -iv" \
	rs="rsync -av --progress --stats" \
	mv="mv -iv" \
	rm="rm -v" \
	mkdir="mkdir -pv" \
	md="mkdir" \
	r2s="export ROS_DOMAIN_ID=42; source /opt/ros/humble/setup.zsh" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x" \
	ytd="yt-dlp --add-metadata -i" \
	ytda="ytd -x" \
	hx="helix" \
	ccat="highlight --out-format=ansi" \
	starwars="telnet towel.blinkenlights.nl" \
	cram="sudo zsh -c 'echo 3 > /proc/sys/vm/drop_caches' && free -h" \
	performance="echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference" \
	powersave="echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | sed \"s/save//g\" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference" \
  bakkesmod="WINEFSYNC=1 protontricks -c 'wine ~/Games/bakkesmod.exe' 252950" \
  snvim="EDITOR=nvim sudoedit" \
  gnvim="goneovim" \
  termuxusb="adb forward tcp:8022 tcp:8022; ssh localhost -p 8022"

# scripts
alias \
	bandwidth="~/.config/scripts/bandwidth.sh" \
	cache="~/.config/scripts/cache-clean.sh" \
	pipes="~/.config/scripts/pipes.sh" \
	myip="curl ipinfo.io/ip && printf '\n'" \
	simplettt="~/.config/scripts/simplettt.sh" \
	wclall="cat \$(find ./ -type f) | wc -l" \
	scrsh="yes | wf-recorder -m avi -f >(ffplay -window_title Screenshare -f avi -) --geometry=\"\$(slurp -o)\"; pkill ffplay 2>&1 >/dev/null; pkill wf-recorder 2>&1 >/dev/null"

