#!/bin/sh

# commands
alias \
	grep="grep --color" \
	ls="exa --group-directories-first" \
	ll="ls -lSh" \
	lls="clear; ls" \
	l="ll -a" \
	la="ls -a" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkdir="mkdir -pv" \
	md="mkdir" \
	r2s="export ROS_DOMAIN_ID=42; source /opt/ros/humble/setup.zsh" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x" \
	hx="helix" \
	ccat="highlight --out-format=ansi" \
	starwars="telnet towel.blinkenlights.nl" \
	cram="sudo zsh -c 'echo 3 > /proc/sys/vm/drop_caches' && free -h" \
	performance="echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference" \
	powersave="echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | sed \"s/save//g\" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference" \
  bakkesmod="WINEFSYNC=1 protontricks -c 'wine ~/Games/bakkesmod.exe' 252950" \

# scripts
alias \
	bandwidth="~/.config/scripts/bandwidth.sh" \
	cache="~/.config/scripts/cache-clean.sh" \
	pipes="~/.config/scripts/pipes.sh" \
	myip="curl ipinfo.io/ip && printf '\n'" \
	simplettt="~/.config/scripts/simplettt.sh" \
	wclall="cat \$(find ./ -type f) | wc -l"

# only for kitty terminal
[ "$TERM" = "xterm-kitty" ] && pgrep -x kitty > /dev/null && alias ssh="kitty +kitten ssh"

