#!/bin/sh

# commands
alias \
	grep="grep --color" \
	ls="exa" \
    ll="ls -lSh" \
    l="ll" \
    la="ll -a" \
	cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -v" \
    mkdir="mkdir -pv" \
    md="mkdir" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x" \
    ccat="highlight --out-format=ansi" \
    starwars="telnet towel.blinkenlights.nl" \
	code="code-insiders"

# scripts
alias \
    bandwidth="~/.config/scripts/bandwidth.sh" \
	cache="~/.config/scripts/cache-clean.sh" \
    pipes="~/.config/scripts/pipes.sh" \
    myip="curl ipinfo.io/ip && printf '\n'" \
	simplettt="~/.config/scripts/simplettt.sh"

# only for kitty terminal
[ "$TERM" = "xterm-kitty" ] && pgrep -x kitty > /dev/null && alias ssh="kitty +kitten ssh"

