#!/bin/sh

# commands
alias \
	grep="grep --color" \
	ls="exa --group-directories-first" \
    ll="ls -lSh" \
	lls="clear; ls" \
    l="ll -a" \
    la="ls -a" \
	cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -v" \
    mkdir="mkdir -pv" \
    md="mkdir" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x" \
	vi="vim" \
    ccat="highlight --out-format=ansi" \
    starwars="telnet towel.blinkenlights.nl" \
	cram="sudo zsh -c 'echo 3 > /proc/sys/vm/drop_caches' && free -h" \
	performance="echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference" \
	powersave="echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | sed \"s/save//g\" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference"

# scripts
alias \
    bandwidth="~/.config/scripts/bandwidth.sh" \
	cache="~/.config/scripts/cache-clean.sh" \
    pipes="~/.config/scripts/pipes.sh" \
    myip="curl ipinfo.io/ip && printf '\n'" \
	simplettt="~/.config/scripts/simplettt.sh"

# only for kitty terminal
[ "$TERM" = "xterm-kitty" ] && pgrep -x kitty > /dev/null && alias ssh="kitty +kitten ssh"

